# Generated by Django 4.2.1 on 2023-07-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('itempurchase', models.TextField()),
                ('prices', models.TextField()),
                ('quantities', models.TextField()),
            ],
        ),
    ]
