# Generated by Django 4.2.1 on 2023-07-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='itempurchase',
            field=models.TextField(null=True),
        ),
    ]
