# Generated by Django 4.2.1 on 2023-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_itempurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prices',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantities',
            field=models.TextField(null=True),
        ),
    ]
