# Generated by Django 4.2.1 on 2023-07-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_prices_alter_customer_quantities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
