# Generated by Django 4.2.1 on 2023-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_customer_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
